stages:
  - build
  - test

test:mac:
  stage: test
  tags:
    - macos
  script:
    - pwd
    - source ~/.bashrc
    - source activate leaspy
    - script/run_multi_python_interpreter_tests.sh
    - source deactivate

test:linux:
  stage: test
  tags:
    - linux
  script:
    - pwd
    - source ~/.bashrc
    - source activate leaspy
    - script/run_multi_python_interpreter_tests.sh
    - source deactivate
