test:
  image: "python:$VERSION"
  script:
    - python -V
    - pip install pipx
    - pipx ensurepath
    - source ~/.bashrc
    - pipx install poetry
    - which poetry
    - poetry install --with dev
    - source `poetry env info --path`/bin/activate
    - pip freeze
    - make cov
  parallel:
    matrix:
      - VERSION: ["3.9", "3.10", "3.11", "3.12"]
  artifacts:
    when: always
    reports:
      junit: report.xml

docs-build:
  image: "python:3.11"
  script:
    - python -V
    - pip install pipx
    - pipx ensurepath
    - source ~/.bashrc
    - pipx install poetry
    - poetry install --with docs
    - source `poetry env info --path`/bin/activate
    - pip freeze
    - make doc

release-pypi:
  image: "python:3.11"
  rules:
    - if: $CI_COMMIT_TAG
      when: always
  script:
    - python -V
    - pip install pipx
    - pipx ensurepath
    - source ~/.bashrc
    - pipx install poetry
    - poetry build
    - poetry publish -u __token__ -a $PYPI_TOKEN -n

