release-pypi:
  image: "python:3.11"
  rules:
    - if: $CI_COMMIT_TAG
      when: always
  script:
    - python -V
    - pip install pipx
    - pipx ensurepath
    - source ~/.bashrc
    - pipx install poetry
    - poetry build
    - poetry publish -u __token__ -a $PYPI_TOKEN -n

