version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      - pip install poetry
      - poetry config virtualenvs.create false
      - . "$READTHEDOCS_VIRTUALENV_PATH/bin/activate" && poetry install --with docs
      - pip freeze
    pre_build:
      - python traffic/visualize_traffic.py --source github:aramis-lab/leaspy:traffic --output-dir docs/_static/traffic || echo "Warning - Traffic data not available yet"

sphinx:
  configuration: docs/conf.py
