[envs.test]
dependencies = [
  "coverage[toml]>=6.5",
  "pytest",
  "pytest-cov",
]
extra-args = ["-vv"]
randomize = true
parallel = true

[[envs.test.matrix]]
python = ["3.9", "3.10", "3.11"]

[envs.test.scripts]
unit = "pytest tests/unittests"
integration = "pytest tests/integration"
all = "pytest tests"
cov-test = "coverage run -m pytest tests"
cov-report = [
  #"coverage combine",
  "coverage report",
]
cov = [
  "cov-test",
  "cov-report",
]

[envs.lint]
detached = true
dependencies = [
  "ruff>=0.0.166",
]

[envs.lint.scripts]
fmt = [
  "ruff --fix {args:.}",
]

[envs.docs]
features = [
  "docs",
]
python = "3.11"

[envs.docs.scripts]
clean = "rm -rf docs/_build"
build = "sphinx-build docs/ docs/_build/html {args}"
serve = "sphinx-autobuild docs/ docs/_build/html {args}"
